/**
 * Rendering: condensed notes → packable units → one file per part.
 *
 * Supported formats:
 *   markdown — best for NotebookLM, Obsidian, human review;
 *   plain    — pure text, no markup, for models that get distracted by `#`;
 *   json     — one document per object, with metadata, for scripts;
 *   jsonl    — one line per note, the format RAG pipelines and fine-tuning
 *              tools expect;
 *   xml      — `<document>` elements with CDATA, for XML-based ingestion.
 */

import type { ExportFormat, FrontmatterValue, PlanStats } from "../types";
import { applyTemplate, formatCount } from "../util";
import { countTokens } from "../tokens";
import type { PackUnit } from "./chunk";
import type { KnowledgeMap } from "../intel/knowledgeMap";
import { knowledgeMapToMarkdown, knowledgeMapToText } from "../intel/knowledgeMap";
import { stringifyFrontmatter } from "../frontmatter";

export interface RenderedNote {
	id: string;
	path: string;
	title: string;
	body: string;
	tags: string[];
	aliases: string[];
	frontmatter: Record<string, FrontmatterValue>;
	words: number;
	tokens: number;
	chars: number;
	modified: number;
	created: number;
	related: { id: string; title: string; similarity: number }[];
	inbound: number;
	outbound: number;
	/** Notes inside the bundle this note links to (citation ids and titles). */
	links?: { id: string; title: string }[];
	/** Notes inside the bundle that link to this one. */
	backlinks?: { id: string; title: string }[];
	/** Distinct outgoing links that point outside the bundle. */
	outsideLinks?: number;
	summaryApplied: boolean;
	duplicateOf?: string;
	truncated?: boolean;
	boilerplateLines?: number;
	transclusions?: number;
}

export interface RenderOptions {
	format: ExportFormat;
	profileName: string;
	bundleTitle: string;
	includeToc: boolean;
	tocMaxDepth: number;
	/** Truncate the contents list after this many entries (0 = no limit). */
	tocMaxEntries: number;
	includeKnowledgeMap: boolean;
	citationIds: boolean;
	headerTemplate: string;
	footerTemplate: string;
	divider: string;
	noteHeadingLevel: number;
	includeManifest: boolean;
	generatedAt: Date;
	roots: string[];
	stats: PlanStats;
	knowledgeMap?: KnowledgeMap;
	/** Repeat the note header when a note is split across parts. */
	repeatHeaders: boolean;
}

export interface RenderedBundle {
	units: PackUnit[];
	/** Variables available to the header/footer templates. */
	variables: Record<string, string>;
}

export const DEFAULT_HEADER_TEMPLATE = `# {{title}}

> **{{profile}}** · {{notes}} notes · {{words}} words · ~{{tokens}} tokens · generated {{date}}
> Source: {{roots}}
`;

export const DEFAULT_FOOTER_TEMPLATE = `*Generated by Condensated Vault Exporter — {{notes}} notes, {{words}} words, ~{{tokens}} tokens.*`;

export function renderBundle(notes: RenderedNote[], options: RenderOptions): RenderedBundle {
	const stats = options.stats;
	const variables: Record<string, string> = {
		title: options.bundleTitle,
		profile: options.profileName,
		notes: String(notes.length),
		words: formatCount(stats.words),
		words_raw: String(stats.words),
		tokens: formatCount(stats.tokens),
		tokens_raw: String(stats.tokens),
		chars: formatCount(stats.chars),
		date: options.generatedAt.toISOString().slice(0, 19).replace("T", " "),
		date_iso: options.generatedAt.toISOString(),
		roots: options.roots.length > 0 ? options.roots.join(", ") : "(vault root)",
		discovered: String(stats.discovered),
		kept: String(stats.kept),
		dropped: String(stats.droppedByFilter + stats.droppedAsDuplicate + stats.droppedAsStub),
		version: "1.0.0",
	};

	// The header/footer templates are rendered by `assemblePart` (they need the
	// part number); the preamble unit only carries the generated structure.
	const toc = options.includeToc ? renderToc(notes, options) : "";
	const knowledgeMap = options.includeKnowledgeMap && options.knowledgeMap ? renderKnowledgeMap(options) : "";
	const preambleText = [toc, knowledgeMap].filter((part) => part.trim() !== "").join("\n\n");

	const units: PackUnit[] = [];
	const heading = options.noteHeadingLevel;
	if (preambleText !== "") {
		units.push({
			origin: "__bundle__",
			role: "preamble",
			id: "S00",
			title: "Bundle header",
			content: preambleText,
			chars: preambleText.length,
			tokens: countTokens(preambleText),
			splittable: true,
		});
	}

	for (const note of notes) {
		const unit = renderNoteUnit(note, options, heading);
		units.push(unit);
	}

	// The footer is appended per part by `assemblePart` (it is part of the
	// part's own structure, not of the corpus), so it is not a unit here.
	return { units, variables };
}

/* -------------------------------------------------------------------------- */
/*  Per-format rendering                                                       */
/* -------------------------------------------------------------------------- */

function renderNoteUnit(note: RenderedNote, options: RenderOptions, headingLevel: number): PackUnit {
	switch (options.format) {
		case "json":
		case "jsonl":
			return renderJsonUnit(note, options);
		case "xml":
			return renderXmlUnit(note, options);
		case "plain":
			return renderPlainUnit(note, options);
		case "markdown":
		default:
			return renderMarkdownUnit(note, options, headingLevel);
	}
}

function renderMarkdownUnit(note: RenderedNote, options: RenderOptions, headingLevel: number): PackUnit {
	const heading = `${"#".repeat(Math.max(1, Math.min(6, headingLevel)))} ${options.citationIds ? `${note.id} · ` : ""}${note.title}`;
	const meta = markdownMeta(note);
	const body = note.body.trim();
	const content = `${heading}\n\n${meta}\n\n${body}`.trimEnd();
	return {
		origin: note.path,
		role: "document",
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		header: options.repeatHeaders ? `${heading}\n\n${meta}` : undefined,
		splittable: true,
	};
}

function markdownMeta(note: RenderedNote): string {
	const parts: string[] = [`\`${note.path}\``];
	parts.push(`${formatCount(note.words)} words`);
	if (note.tags.length > 0) parts.push(note.tags.slice(0, 8).map((t) => `#${t}`).join(" "));
	if (note.modified > 0) parts.push(`updated ${isoDate(note.modified)}`);
	if (note.inbound + note.outbound > 0) parts.push(`${note.inbound} in / ${note.outbound} out links`);
	const links = note.links ?? [];
	if (links.length > 0) parts.push(`links: ${links.slice(0, 6).map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const backlinks = note.backlinks ?? [];
	if (backlinks.length > 0) parts.push(`linked from: ${backlinks.slice(0, 6).map((l) => `${l.id} ${l.title}`).join(", ")}`);
	if ((note.outsideLinks ?? 0) > 0) parts.push(`${note.outsideLinks} link(s) outside this bundle`);
	if (note.related.length > 0) {
		parts.push(`related: ${note.related.slice(0, 4).map((r) => `${r.id} ${r.title}`).join(", ")}`);
	}
	const flags: string[] = [];
	if (note.summaryApplied) flags.push("summarized");
	if (note.truncated) flags.push("truncated");
	if (note.duplicateOf) flags.push(`duplicate of ${note.duplicateOf}`);
	if (note.transclusions) flags.push(`${note.transclusions} transclusion(s) inlined`);
	if (flags.length > 0) parts.push(`*${flags.join(", ")}*`);
	return `> ${parts.join(" · ")}`;
}

function renderPlainUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const rule = "=".repeat(78);
	const label = options.citationIds ? `[${note.id}] ` : "";
	const metaParts = [`path: ${note.path}`, `${note.words} words`];
	if (note.tags.length > 0) metaParts.push(`tags: ${note.tags.map((t) => `#${t}`).join(" ")}`);
	if (note.modified > 0) metaParts.push(`updated: ${isoDate(note.modified)}`);
	const linkRefs = (note.links ?? []).slice(0, 6);
	if (linkRefs.length > 0) metaParts.push(`links to: ${linkRefs.map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const backrefs = (note.backlinks ?? []).slice(0, 6);
	if (backrefs.length > 0) metaParts.push(`linked from: ${backrefs.map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const content = `${rule}\n${label}${note.title.toUpperCase()}\n${metaParts.join(" | ")}\n${rule}\n\n${stripMarkdown(note.body).trim()}`;
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		header: options.repeatHeaders ? `${rule}\n${label}${note.title.toUpperCase()}` : undefined,
		splittable: true,
	};
}

function renderJsonUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const payload = {
		id: options.citationIds ? note.id : undefined,
		title: note.title,
		path: note.path,
		tags: note.tags,
		aliases: note.aliases.length > 0 ? note.aliases : undefined,
		metadata: Object.keys(note.frontmatter).length > 0 ? note.frontmatter : undefined,
		created: note.created > 0 ? new Date(note.created).toISOString() : undefined,
		modified: note.modified > 0 ? new Date(note.modified).toISOString() : undefined,
		words: note.words,
		tokens: note.tokens,
		links: {
			inbound: note.inbound,
			outbound: note.outbound,
			// Cross-references inside the bundle, as citation ids.
			to: (note.links ?? []).map((l) => l.id),
			from: (note.backlinks ?? []).map((l) => l.id),
			outside: note.outsideLinks || undefined,
		},
		related: note.related.length > 0 ? note.related.map((r) => ({ id: r.id, title: r.title, similarity: r.similarity })) : undefined,
		summaryApplied: note.summaryApplied || undefined,
		truncated: note.truncated || undefined,
		duplicateOf: note.duplicateOf,
		content: note.body,
	};
	const content =
		options.format === "jsonl" ? JSON.stringify(payload) : JSON.stringify(payload, null, 2);
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		splittable: options.format === "jsonl",
	};
}

function renderXmlUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const attributes: string[] = [];
	if (options.citationIds) attributes.push(`id="${escapeXml(note.id)}"`);
	attributes.push(`path="${escapeXml(note.path)}"`);
	attributes.push(`title="${escapeXml(note.title)}"`);
	attributes.push(`words="${note.words}"`);
	if (note.tags.length > 0) attributes.push(`tags="${escapeXml(note.tags.join(","))}"`);
	if (note.modified > 0) attributes.push(`modified="${isoDate(note.modified)}"`);
	const meta: string[] = [];
	for (const [key, value] of Object.entries(note.frontmatter)) {
		if (value === null || typeof value === "object") continue;
		meta.push(`    <field name="${escapeXml(key)}">${escapeXml(String(value))}</field>`);
	}
	const related = note.related.map(
		(r) => `    <related id="${escapeXml(r.id)}" similarity="${r.similarity.toFixed(3)}">${escapeXml(r.title)}</related>`,
	);
	const references = (note.links ?? []).map(
		(l) => `    <link target="${escapeXml(l.id)}">${escapeXml(l.title)}</link>`,
	);
	const backrefs = (note.backlinks ?? []).map(
		(l) => `    <backlink source="${escapeXml(l.id)}">${escapeXml(l.title)}</backlink>`,
	);
	const content =
		`  <document ${attributes.join(" ")}>\n` +
		(meta.length > 0 ? `  <metadata>\n${meta.join("\n")}\n  </metadata>\n` : "") +
		(related.length > 0 ? `  <relations>\n${related.join("\n")}\n  </relations>\n` : "") +
		(references.length + backrefs.length > 0
			? `  <references${(note.outsideLinks ?? 0) > 0 ? ` outside="${note.outsideLinks}"` : ""}>\n${[...references, ...backrefs].join("\n")}\n  </references>\n`
			: "") +
		`    <content><![CDATA[${note.body.replace(/]]>/g, "]]]]><![CDATA[>")}]]></content>\n` +
		`  </document>`;
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		splittable: true,
	};
}

/* -------------------------------------------------------------------------- */
/*  Table of contents & knowledge map                                          */
/* -------------------------------------------------------------------------- */

function renderToc(notes: RenderedNote[], options: RenderOptions): string {
	if (notes.length === 0) return "";
	const byFolder = new Map<string, RenderedNote[]>();
	for (const note of notes) {
		const folder = note.path.includes("/") ? note.path.slice(0, note.path.lastIndexOf("/")) : "(root)";
		const list = byFolder.get(folder);
		if (list) list.push(note);
		else byFolder.set(folder, [note]);
	}
	const cap = options.tocMaxEntries > 0 ? options.tocMaxEntries : Number.POSITIVE_INFINITY;
	const lines: string[] = [];
	let listed = 0;
	let skipped = 0;
	const noteLine = (note: RenderedNote, markdown: boolean): string => {
		if (listed >= cap) {
			skipped++;
			return "";
		}
		listed++;
		if (!markdown) return `  ${options.citationIds ? `[${note.id}] ` : ""}${note.title} (${note.path})`;
		const label = options.citationIds ? `\`${note.id}\` ${note.title} — *${formatCount(note.words)} words*` : `${note.title} — *${formatCount(note.words)} words*`;
		return `- ${label}`;
	};
	if (options.format === "markdown") {
		lines.push("## Contents", "");
		const folders = Array.from(byFolder.keys()).sort((a, b) => a.localeCompare(b));
		for (const folder of folders) {
			const entries = byFolder.get(folder)!;
			if (folders.length > 1) lines.push(`**${folder}/** (${entries.length})`, "");
			for (const note of entries) {
				const line = noteLine(note, true);
				if (line !== "") lines.push(line);
			}
			lines.push("");
		}
	} else if (options.format === "plain") {
		lines.push("CONTENTS", "");
		for (const note of notes) {
			const line = noteLine(note, false);
			if (line !== "") lines.push(line);
		}
		lines.push("");
	} else {
		return "";
	}
	if (skipped > 0) {
		lines.push(
			options.format === "markdown"
				? `*(…and ${formatCount(skipped)} more notes — the full list is in the manifest.)*`
				: `…and ${formatCount(skipped)} more notes (full list in the manifest).`,
		);
	}
	return lines.join("\n").trim();
}

function renderKnowledgeMap(options: RenderOptions): string {
	const map = options.knowledgeMap;
	if (!map) return "";
	if (options.format === "markdown") return knowledgeMapToMarkdown(map);
	if (options.format === "plain") return knowledgeMapToText(map);
	return "";
}

/* -------------------------------------------------------------------------- */
/*  Part assembly                                                              */
/* -------------------------------------------------------------------------- */

export interface PartAssemblyOptions {
	format: ExportFormat;
	header: string;
	footer: string;
	divider: string;
	partIndex: number;
	partTotal: number;
	/** 1-based volume this part belongs to (only used when there is > 1). */
	volumeIndex?: number;
	volumeTotal?: number;
	variables: Record<string, string>;
	title: string;
	stats: PlanStats;
	generatedAt: Date;
	citationIds: boolean;
	includeManifest: boolean;
	profile: { id: string; name: string };
	includeNoteSeparators: boolean;
}

/** Wraps the concatenated units of one part into a complete document. */
export function assemblePart(units: PackUnit[], options: PartAssemblyOptions): string {
	const variables: Record<string, string> = {
		...options.variables,
		part: String(options.partIndex + 1),
		total: String(options.partTotal),
		part_index: String(options.partIndex),
		volume: String(options.volumeIndex ?? 1),
		volume_total: String(options.volumeTotal ?? 1),
	};
	const volume =
		options.volumeTotal !== undefined && options.volumeTotal > 1
			? { index: options.volumeIndex ?? 1, total: options.volumeTotal }
			: undefined;
	const header = appendPartNotice(
		applyTemplate(options.header, variables).trim(),
		options.partIndex,
		options.partTotal,
		options.format,
		variables.title,
		volume,
	);
	const footer = options.footer.trim() === "" ? "" : applyTemplate(options.footer, variables).trim();

	switch (options.format) {
		case "json": {
			const documents = units
				.filter((unit) => unit.role !== "preamble" && unit.role !== "footer")
				.map((unit) => {
					try {
						return JSON.parse(unit.content) as unknown;
					} catch {
						return { content: unit.content };
					}
				});
			const payload: Record<string, unknown> = {
				bundle: {
					title: variables.title,
					profile: options.profile.name,
					profileId: options.profile.id,
					format: "json",
					generatedAt: options.generatedAt.toISOString(),
					part: options.partIndex + 1,
					parts: options.partTotal,
					notes: options.stats.kept,
					words: options.stats.words,
					tokens: options.stats.tokens,
					preamble: units.filter((unit) => unit.role === "preamble").map((unit) => unit.content).join("\n\n") || undefined,
					footer: units.filter((unit) => unit.role === "footer").map((unit) => unit.content).join("\n\n") || undefined,
				},
				documents,
			};
			return JSON.stringify(payload, null, 2);
		}
		case "jsonl": {
			const lines: string[] = [];
			lines.push(
				JSON.stringify({
					type: "bundle",
					title: variables.title,
					profile: options.profile.name,
					profileId: options.profile.id,
					generatedAt: options.generatedAt.toISOString(),
					part: options.partIndex + 1,
					parts: options.partTotal,
					notes: options.stats.kept,
					words: options.stats.words,
					tokens: options.stats.tokens,
					header: header || undefined,
				}),
			);
			for (const unit of units) {
				if (unit.role === "preamble") {
					lines.push(JSON.stringify({ type: "preamble", text: unit.content }));
					continue;
				}
				if (unit.role === "footer") {
					lines.push(JSON.stringify({ type: "footer", text: unit.content }));
					continue;
				}
				lines.push(unit.content);
			}
			if (footer && !units.some((unit) => unit.role === "footer")) lines.push(JSON.stringify({ type: "footer", text: footer }));
			return lines.join("\n");
		}
		case "xml": {
			const documents = units.filter((unit) => unit.role !== "preamble" && unit.role !== "footer").map((unit) => unit.content);
			const preambleUnits = units.filter((unit) => unit.role === "preamble").map((unit) => unit.content).join("\n\n");
			const prologue = `<?xml version="1.0" encoding="UTF-8"?>\n<bundle title="${escapeXml(variables.title)}" profile="${escapeXml(
				options.profile.name,
			)}" generatedAt="${options.generatedAt.toISOString()}" part="${options.partIndex + 1}" parts="${options.partTotal}" notes="${
				options.stats.kept
			}" words="${options.stats.words}" tokens="${options.stats.tokens}">`;
			const preamble = [header, preambleUnits].filter((part) => part.trim() !== "").join("\n\n");
			const headerXml = preamble ? `\n  <preamble><![CDATA[${preamble.replace(/]]>/g, "]]]]><![CDATA[>")}]]></preamble>` : "";
			const footerXml = footer ? `\n  <postamble><![CDATA[${footer.replace(/]]>/g, "]]]]><![CDATA[>")}]]></postamble>` : "";
			return `${prologue}${headerXml}\n${documents.join("\n")}${footerXml}\n</bundle>`;
		}
		default: {
			const separator = options.includeNoteSeparators ? options.divider : "\n\n";
			const body = units
				.filter((unit) => unit.role !== "footer")
				.map((unit) => unit.content.trimEnd());
			// One blank line around the divider: joining the pieces with "\n\n"
			// *and* inserting a separator between them produced three.
			const chunks = [header, body.join(`\n\n${separator.trim()}\n\n`)];
			if (footer) chunks.push(footer);
			const text = chunks.filter((chunk) => chunk.trim() !== "").join("\n\n");
			return text.replace(/\n{4,}/g, "\n\n\n");
		}
	}
}

function appendPartNotice(
	header: string,
	index: number,
	total: number,
	format: ExportFormat,
	title: string,
	volume?: { index: number; total: number },
): string {
	if (total <= 1 && !volume) return header;
	const notice = [
		total > 1 ? `Part ${index + 1} of ${total}` : null,
		volume ? `volume ${volume.index} of ${volume.total}` : null,
	]
		.filter(Boolean)
		.join(" · ");
	switch (format) {
		case "markdown":
			return `${header}\n\n> 📦 **${notice}** — “${title}”`;
		case "plain":
			return `${header}\n${notice}`;
		default:
			return header;
	}
}

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                    */
/* -------------------------------------------------------------------------- */

function isoDate(ms: number): string {
	return new Date(ms).toISOString().slice(0, 10);
}

function escapeXml(text: string): string {
	return text.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[c] ?? c);
}

/** Rough markdown→text conversion for the `plain` format. */
export function stripMarkdown(text: string): string {
	return text
		.replace(/!\[([^\]]*)\]\([^)]*\)/g, "[image: $1]")
		.replace(/\[([^\]]*)\]\(([^)]*)\)/g, "$1 ($2)")
		.replace(/^\s{0,3}#{1,6}\s*/gm, "")
		.replace(/^\s*>\s?/gm, "")
		.replace(/(\*\*|__)(.*?)\1/g, "$2")
		.replace(/(\*|_)(?=\S)(.*?)(?<=\S)\1/g, "$2")
		.replace(/`{1,3}([^`]+)`{1,3}/g, "$1")
		.replace(/~~(.*?)~~/g, "$1")
		.replace(/^\s*([-*+])\s+/gm, "• ")
		.replace(/\n{3,}/g, "\n\n");
}

export { stringifyFrontmatter };
