/**
 * Rendering: condensed notes → packable units → one file per part.
 *
 * Supported formats:
 *   markdown — best for NotebookLM, Obsidian, human review;
 *   plain    — pure text, no markup, for models that get distracted by `#`;
 *   json     — one document per object, with metadata, for scripts;
 *   jsonl    — one line per note, the format RAG pipelines and fine-tuning
 *              tools expect;
 *   xml      — `<document>` elements with CDATA, for XML-based ingestion.
 */

import type { ExportFormat, FrontmatterValue, PlanStats } from "../types";
import { applyTemplate, formatCount } from "../util";
import { countTokens } from "../tokens";
import { countWords } from "../markdown/syntax";
import { splitUnit, type ChunkOptions, type PackUnit } from "./chunk";
import type { KnowledgeMap } from "../intel/knowledgeMap";
import { knowledgeMapToMarkdown, knowledgeMapToText } from "../intel/knowledgeMap";
import { stringifyFrontmatter } from "../frontmatter";

export interface RenderedNote {
	id: string;
	path: string;
	title: string;
	body: string;
	tags: string[];
	aliases: string[];
	frontmatter: Record<string, FrontmatterValue>;
	words: number;
	tokens: number;
	chars: number;
	modified: number;
	created: number;
	related: { id: string; title: string; similarity: number }[];
	inbound: number;
	outbound: number;
	/** Notes inside the bundle this note links to (citation ids and titles). */
	links?: { id: string; title: string }[];
	/** Notes inside the bundle that link to this one. */
	backlinks?: { id: string; title: string }[];
	/** Distinct outgoing links that point outside the bundle. */
	outsideLinks?: number;
	summaryApplied: boolean;
	duplicateOf?: string;
	truncated?: boolean;
	boilerplateLines?: number;
	transclusions?: number;
	/** Set when a note became several JSONL records. */
	chunk?: { index: number; total: number };
}

export interface RenderOptions {
	format: ExportFormat;
	profileName: string;
	bundleTitle: string;
	includeToc: boolean;
	tocMaxDepth: number;
	/** Truncate the contents list after this many entries (0 = no limit). */
	tocMaxEntries: number;
	includeKnowledgeMap: boolean;
	citationIds: boolean;
	headerTemplate: string;
	footerTemplate: string;
	divider: string;
	noteHeadingLevel: number;
	includeManifest: boolean;
	generatedAt: Date;
	roots: string[];
	stats: PlanStats;
	knowledgeMap?: KnowledgeMap;
	/** Repeat the note header when a note is split across parts. */
	repeatHeaders: boolean;
	/**
	 * JSONL only: the largest record a part can hold. A note that would produce
	 * a bigger line is split into several complete records first — a cut line is
	 * not JSON any more, and a JSONL file is only useful if every line parses.
	 */
	maxRecordTokens?: number;
	/** Cut and overlap settings used when a record has to be split. */
	chunking?: ChunkOptions;
	/** Notes in the bundle, when the caller already knows (kept for templates). */
	noteCount?: number;
}

export interface RenderedBundle {
	units: PackUnit[];
	/** Variables available to the header/footer templates. */
	variables: Record<string, string>;
}

export const DEFAULT_HEADER_TEMPLATE = `# {{title}}

> **{{profile}}** · {{notes}} notes · {{words}} words · ~{{tokens}} tokens · generated {{date}}
> Source: {{roots}}
`;

export const DEFAULT_FOOTER_TEMPLATE = `*Generated by Condensated Vault Exporter — {{notes}} notes, {{words}} words, ~{{tokens}} tokens.*`;

export function renderVariables(options: RenderOptions): Record<string, string> {
	const stats = options.stats;
	const variables: Record<string, string> = {
		title: options.bundleTitle,
		profile: options.profileName,
		notes: String(options.noteCount ?? options.stats.kept),
		words: formatCount(stats.words),
		words_raw: String(stats.words),
		tokens: formatCount(stats.tokens),
		tokens_raw: String(stats.tokens),
		chars: formatCount(stats.chars),
		date: options.generatedAt.toISOString().slice(0, 19).replace("T", " "),
		date_iso: options.generatedAt.toISOString(),
		roots: options.roots.length > 0 ? options.roots.join(", ") : "(vault root)",
		discovered: String(stats.discovered),
		kept: String(stats.kept),
		dropped: String(stats.droppedByFilter + stats.droppedAsDuplicate + stats.droppedAsStub),
		version: "1.0.0",
	};
	return variables;
}

export function renderBundle(notes: RenderedNote[], options: RenderOptions): RenderedBundle {
	const variables = renderVariables(options);
	const stats = options.stats;

	// The header/footer templates are rendered by `assemblePart` (they need the
	// part number); the preamble unit only carries the generated structure.
	const toc = options.includeToc ? renderToc(notes, options) : "";
	const knowledgeMap = options.includeKnowledgeMap && options.knowledgeMap ? renderKnowledgeMap(options) : "";
	const preambleText = [toc, knowledgeMap].filter((part) => part.trim() !== "").join("\n\n");

	const units: PackUnit[] = [];
	const heading = options.noteHeadingLevel;
	if (preambleText !== "") {
		units.push({
			origin: "__bundle__",
			role: "preamble",
			id: "S00",
			title: "Bundle header",
			content: preambleText,
			chars: preambleText.length,
			tokens: countTokens(preambleText),
			splittable: true,
		});
	}

	for (const note of notes) {
		for (const piece of splitNoteRecords(note, options)) units.push(renderNoteUnit(piece, options, heading));
	}

	// The footer is appended per part by `assemblePart` (it is part of the
	// part's own structure, not of the corpus), so it is not a unit here.
	return { units, variables };
}

/* -------------------------------------------------------------------------- */
/*  Per-format rendering                                                       */
/* -------------------------------------------------------------------------- */

const DEFAULT_SPLIT: ChunkOptions = {
	mode: "maxTokens",
	maxChars: 0,
	maxTokens: 0,
	maxWords: 0,
	overlapTokens: 0,
	splitAtLevel: 3,
	repeatHeader: false,
};

/**
 * Structured formats: turns a note into as many complete records as the part
 * budget needs.
 *
 * The chunker cuts oversized *units* at paragraph or heading boundaries, which
 * is right for prose but wrong for a machine format: a JSON line cut in half is
 * not JSON any more, and an XML part that opens `<document>` without closing it
 * does not parse at all. Here the note body is cut first and every piece is
 * serialised on its own, so a part contains whole records only — which is also
 * the shape a RAG pipeline wants (same metadata, `chunk: {index, total}`, ids
 * `S07.1`, `S07.2`).
 */
export function splitNoteRecords(note: RenderedNote, options: RenderOptions): RenderedNote[] {
	if (options.format === "markdown" || options.format === "plain" || options.format === "html") return [note];
	const limit = options.maxRecordTokens ?? 0;
	if (limit <= 0) return [note];
	const recordTokens =
		options.format === "xml" ? renderXmlUnit(note, options).tokens : renderJsonUnit(note, options).tokens;
	if (recordTokens <= limit) return [note];
	const bodyTokens = countTokens(note.body);
	// The serialised body is not the body: a pretty-printed JSON record repeats
	// the indentation on every line and escapes every newline, so its envelope
	// grows with the note. The measured ratio between the whole record and the
	// body is therefore the scale a piece has to shrink by — subtracting a fixed
	// envelope instead is what made a 4 000-token note unsplittable.
	const ratio = limit / recordTokens;
	const bodyBudget = Math.max(64, Math.floor(bodyTokens * ratio));
	if (bodyBudget >= bodyTokens) return [note];
	const pieces = splitUnit(
		{
			origin: note.path,
			id: note.id,
			title: note.title,
			content: note.body,
			chars: note.body.length,
			tokens: bodyTokens,
			splittable: true,
		},
		bodyBudget,
		options.chunking ?? DEFAULT_SPLIT,
	);
	if (pieces.length <= 1) return [note];
	return pieces.map((piece, index) => ({
		...note,
		id: piece.id,
		title: piece.title,
		body: piece.content,
		words: countWords(piece.content),
		tokens: piece.tokens,
		chars: piece.content.length,
		chunk: { index: index + 1, total: pieces.length },
	}));
}

function renderNoteUnit(note: RenderedNote, options: RenderOptions, headingLevel: number): PackUnit {
	switch (options.format) {
		case "json":
		case "jsonl":
			return renderJsonUnit(note, options);
		case "xml":
			return renderXmlUnit(note, options);
		case "html":
			return renderHtmlUnit(note, options);
		case "plain":
			return renderPlainUnit(note, options);
		case "markdown":
		default:
			return renderMarkdownUnit(note, options, headingLevel);
	}
}

function renderMarkdownUnit(note: RenderedNote, options: RenderOptions, headingLevel: number): PackUnit {
	const heading = `${"#".repeat(Math.max(1, Math.min(6, headingLevel)))} ${options.citationIds ? `${note.id} · ` : ""}${note.title}`;
	const meta = markdownMeta(note);
	const body = note.body.trim();
	const content = `${heading}\n\n${meta}\n\n${body}`.trimEnd();
	return {
		origin: note.path,
		role: "document",
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		header: options.repeatHeaders ? `${heading}\n\n${meta}` : undefined,
		splittable: true,
	};
}

function markdownMeta(note: RenderedNote): string {
	const parts: string[] = [`\`${note.path}\``];
	parts.push(`${formatCount(note.words)} words`);
	if (note.tags.length > 0) parts.push(note.tags.slice(0, 8).map((t) => `#${t}`).join(" "));
	if (note.modified > 0) parts.push(`updated ${isoDate(note.modified)}`);
	if (note.inbound + note.outbound > 0) parts.push(`${note.inbound} in / ${note.outbound} out links`);
	const links = note.links ?? [];
	if (links.length > 0) parts.push(`links: ${links.slice(0, 6).map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const backlinks = note.backlinks ?? [];
	if (backlinks.length > 0) parts.push(`linked from: ${backlinks.slice(0, 6).map((l) => `${l.id} ${l.title}`).join(", ")}`);
	if ((note.outsideLinks ?? 0) > 0) parts.push(`${note.outsideLinks} link(s) outside this bundle`);
	if (note.related.length > 0) {
		parts.push(`related: ${note.related.slice(0, 4).map((r) => `${r.id} ${r.title}`).join(", ")}`);
	}
	const flags: string[] = [];
	if (note.summaryApplied) flags.push("summarized");
	if (note.truncated) flags.push("truncated");
	if (note.duplicateOf) flags.push(`duplicate of ${note.duplicateOf}`);
	if (note.transclusions) flags.push(`${note.transclusions} transclusion(s) inlined`);
	if (flags.length > 0) parts.push(`*${flags.join(", ")}*`);
	return `> ${parts.join(" · ")}`;
}

function renderPlainUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const rule = "=".repeat(78);
	const label = options.citationIds ? `[${note.id}] ` : "";
	const metaParts = [`path: ${note.path}`, `${note.words} words`];
	if (note.tags.length > 0) metaParts.push(`tags: ${note.tags.map((t) => `#${t}`).join(" ")}`);
	if (note.modified > 0) metaParts.push(`updated: ${isoDate(note.modified)}`);
	const linkRefs = (note.links ?? []).slice(0, 6);
	if (linkRefs.length > 0) metaParts.push(`links to: ${linkRefs.map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const backrefs = (note.backlinks ?? []).slice(0, 6);
	if (backrefs.length > 0) metaParts.push(`linked from: ${backrefs.map((l) => `${l.id} ${l.title}`).join(", ")}`);
	const content = `${rule}\n${label}${note.title.toUpperCase()}\n${metaParts.join(" | ")}\n${rule}\n\n${stripMarkdown(note.body).trim()}`;
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		header: options.repeatHeaders ? `${rule}\n${label}${note.title.toUpperCase()}` : undefined,
		splittable: true,
	};
}

function renderJsonUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const payload = {
		id: options.citationIds ? note.id : undefined,
		title: note.title,
		path: note.path,
		tags: note.tags,
		aliases: note.aliases.length > 0 ? note.aliases : undefined,
		metadata: Object.keys(note.frontmatter).length > 0 ? note.frontmatter : undefined,
		created: note.created > 0 ? new Date(note.created).toISOString() : undefined,
		modified: note.modified > 0 ? new Date(note.modified).toISOString() : undefined,
		words: note.words,
		tokens: note.tokens,
		links: {
			inbound: note.inbound,
			outbound: note.outbound,
			// Cross-references inside the bundle, as citation ids.
			to: (note.links ?? []).map((l) => l.id),
			from: (note.backlinks ?? []).map((l) => l.id),
			outside: note.outsideLinks || undefined,
		},
		related: note.related.length > 0 ? note.related.map((r) => ({ id: r.id, title: r.title, similarity: r.similarity })) : undefined,
		summaryApplied: note.summaryApplied || undefined,
		truncated: note.truncated || undefined,
		duplicateOf: note.duplicateOf,
		chunk: note.chunk,
		content: note.body,
	};
	const content =
		options.format === "jsonl" ? JSON.stringify(payload) : JSON.stringify(payload, null, 2);
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		// One record, one line: the chunker must never cut it. Notes that are
		// too big for a part were already split into several records.
		splittable: false,
	};
}

function renderXmlUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const attributes: string[] = [];
	if (options.citationIds) attributes.push(`id="${escapeXml(note.id)}"`);
	attributes.push(`path="${escapeXml(note.path)}"`);
	attributes.push(`title="${escapeXml(note.title)}"`);
	attributes.push(`words="${note.words}"`);
	// A note that had to be cut into several documents says so, so a reader can
	// put the pieces back together instead of treating them as duplicates.
	if (note.chunk) attributes.push(`chunk="${note.chunk.index}/${note.chunk.total}"`);
	if (note.tags.length > 0) attributes.push(`tags="${escapeXml(note.tags.join(","))}"`);
	if (note.modified > 0) attributes.push(`modified="${isoDate(note.modified)}"`);
	const meta: string[] = [];
	for (const [key, value] of Object.entries(note.frontmatter)) {
		if (value === null || typeof value === "object") continue;
		meta.push(`    <field name="${escapeXml(key)}">${escapeXml(String(value))}</field>`);
	}
	const related = note.related.map(
		(r) => `    <related id="${escapeXml(r.id)}" similarity="${r.similarity.toFixed(3)}">${escapeXml(r.title)}</related>`,
	);
	const references = (note.links ?? []).map(
		(l) => `    <link target="${escapeXml(l.id)}">${escapeXml(l.title)}</link>`,
	);
	const backrefs = (note.backlinks ?? []).map(
		(l) => `    <backlink source="${escapeXml(l.id)}">${escapeXml(l.title)}</backlink>`,
	);
	const content =
		`  <document ${attributes.join(" ")}>\n` +
		(meta.length > 0 ? `  <metadata>\n${meta.join("\n")}\n  </metadata>\n` : "") +
		(related.length > 0 ? `  <relations>\n${related.join("\n")}\n  </relations>\n` : "") +
		(references.length + backrefs.length > 0
			? `  <references${(note.outsideLinks ?? 0) > 0 ? ` outside="${note.outsideLinks}"` : ""}>\n${[...references, ...backrefs].join("\n")}\n  </references>\n`
			: "") +
		`    <content><![CDATA[${note.body.replace(/]]>/g, "]]]]><![CDATA[>")}]]></content>\n` +
		`  </document>`;
	return {
		origin: note.path,
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(content),
		// A `<document>` element is a record: it must not be cut in half.
		splittable: false,
	};
}

function renderHtmlUnit(note: RenderedNote, options: RenderOptions): PackUnit {
	const anchorId = escapeXml(note.id || note.path);
	const badge = options.citationIds && note.id ? `<span class="cve-badge">${escapeXml(note.id)}</span> ` : "";
	const tagsHtml =
		note.tags.length > 0
			? note.tags
					.slice(0, 8)
					.map((t) => `<span class="cve-tag">#${escapeXml(t)}</span>`)
					.join(" ")
			: "";
	const links = note.links ?? [];
	const linksHtml =
		links.length > 0
			? `<span class="cve-meta-item">links: ${links
					.slice(0, 6)
					.map((l) => `<a href="#${escapeXml(l.id)}">${escapeXml(l.id)} ${escapeXml(l.title)}</a>`)
					.join(", ")}</span>`
			: "";
	const backlinks = note.backlinks ?? [];
	const backlinksHtml =
		backlinks.length > 0
			? `<span class="cve-meta-item">linked from: ${backlinks
					.slice(0, 6)
					.map((l) => `<a href="#${escapeXml(l.id)}">${escapeXml(l.id)} ${escapeXml(l.title)}</a>`)
					.join(", ")}</span>`
			: "";
	const metaItems = [
		`<code>${escapeXml(note.path)}</code>`,
		`<span>${formatCount(note.words)} words</span>`,
		note.modified > 0 ? `<span>updated ${isoDate(note.modified)}</span>` : "",
		tagsHtml,
		linksHtml,
		backlinksHtml,
	]
		.filter(Boolean)
		.join(" · ");
	const bodyHtml = markdownToHtml(note.body);
	const content = [
		`<article class="cve-doc" id="${anchorId}" data-id="${escapeXml(note.id.toLowerCase())}" data-title="${escapeXml(note.title.toLowerCase())}" data-path="${escapeXml(note.path.toLowerCase())}" data-tags="${escapeXml(note.tags.join(" ").toLowerCase())}">`,
		`  <header class="cve-doc-header">`,
		`    <h2 class="cve-doc-title">${badge}${escapeXml(note.title)}</h2>`,
		`    <div class="cve-doc-meta">${metaItems}</div>`,
		`  </header>`,
		`  <div class="cve-doc-body">${bodyHtml}</div>`,
		`</article>`,
	].join("\n");
	return {
		origin: note.path,
		role: "document",
		id: note.id,
		title: note.title,
		content,
		chars: content.length,
		tokens: countTokens(note.body) + 25,
		splittable: false,
	};
}

/* -------------------------------------------------------------------------- */
/*  Table of contents & knowledge map                                          */
/* -------------------------------------------------------------------------- */

function renderToc(notes: RenderedNote[], options: RenderOptions): string {
	if (notes.length === 0) return "";
	const byFolder = new Map<string, RenderedNote[]>();
	for (const note of notes) {
		const folder = note.path.includes("/") ? note.path.slice(0, note.path.lastIndexOf("/")) : "(root)";
		const list = byFolder.get(folder);
		if (list) list.push(note);
		else byFolder.set(folder, [note]);
	}
	const cap = options.tocMaxEntries > 0 ? options.tocMaxEntries : Number.POSITIVE_INFINITY;
	const lines: string[] = [];
	let listed = 0;
	let skipped = 0;
	const noteLine = (note: RenderedNote, markdown: boolean): string => {
		if (listed >= cap) {
			skipped++;
			return "";
		}
		listed++;
		if (!markdown) return `  ${options.citationIds ? `[${note.id}] ` : ""}${note.title} (${note.path})`;
		const label = options.citationIds ? `\`${note.id}\` ${note.title} — *${formatCount(note.words)} words*` : `${note.title} — *${formatCount(note.words)} words*`;
		return `- ${label}`;
	};
	if (options.format === "markdown") {
		lines.push("## Contents", "");
		const folders = Array.from(byFolder.keys()).sort((a, b) => a.localeCompare(b));
		for (const folder of folders) {
			const entries = byFolder.get(folder)!;
			if (folders.length > 1) lines.push(`**${folder}/** (${entries.length})`, "");
			for (const note of entries) {
				const line = noteLine(note, true);
				if (line !== "") lines.push(line);
			}
			lines.push("");
		}
	} else if (options.format === "plain") {
		lines.push("CONTENTS", "");
		for (const note of notes) {
			const line = noteLine(note, false);
			if (line !== "") lines.push(line);
		}
		lines.push("");
	} else if (options.format === "html") {
		lines.push(`<nav class="cve-toc"><h2>Contents</h2><ul>`);
		for (const note of notes) {
			if (listed >= cap) {
				skipped++;
				continue;
			}
			listed++;
			const anchor = escapeXml(note.id || note.path);
			const badge = options.citationIds && note.id ? `<span class="cve-badge">${escapeXml(note.id)}</span> ` : "";
			lines.push(
				`  <li><a href="#${anchor}">${badge}${escapeXml(note.title)}</a> <span class="cve-muted">(${formatCount(note.words)} words)</span></li>`,
			);
		}
		lines.push(`</ul></nav>`);
	} else {
		return "";
	}
	if (skipped > 0) {
		lines.push(
			options.format === "markdown" || options.format === "html"
				? `*(…and ${formatCount(skipped)} more notes — the full list is in the manifest.)*`
				: `…and ${formatCount(skipped)} more notes (full list in the manifest).`,
		);
	}
	return lines.join("\n").trim();
}

function renderKnowledgeMap(options: RenderOptions): string {
	const map = options.knowledgeMap;
	if (!map) return "";
	if (options.format === "markdown") return knowledgeMapToMarkdown(map);
	if (options.format === "plain") return knowledgeMapToText(map);
	if (options.format === "html") {
		return `<section class="cve-map"><details open><summary>Corpus Knowledge Map</summary><div class="cve-map-body">${markdownToHtml(knowledgeMapToMarkdown(map))}</div></details></section>`;
	}
	return "";
}

/* -------------------------------------------------------------------------- */
/*  Part assembly                                                              */
/* -------------------------------------------------------------------------- */

export interface PartAssemblyOptions {
	format: ExportFormat;
	header: string;
	footer: string;
	divider: string;
	partIndex: number;
	partTotal: number;
	/** 1-based volume this part belongs to (only used when there is > 1). */
	volumeIndex?: number;
	volumeTotal?: number;
	variables: Record<string, string>;
	title: string;
	stats: PlanStats;
	generatedAt: Date;
	citationIds: boolean;
	includeManifest: boolean;
	profile: { id: string; name: string };
	includeNoteSeparators: boolean;
}

/** Wraps the concatenated units of one part into a complete document. */
export function assemblePart(units: PackUnit[], options: PartAssemblyOptions): string {
	const variables: Record<string, string> = {
		...options.variables,
		part: String(options.partIndex + 1),
		total: String(options.partTotal),
		part_index: String(options.partIndex),
		volume: String(options.volumeIndex ?? 1),
		volume_total: String(options.volumeTotal ?? 1),
	};
	const volume =
		options.volumeTotal !== undefined && options.volumeTotal > 1
			? { index: options.volumeIndex ?? 1, total: options.volumeTotal }
			: undefined;
	const header = appendPartNotice(
		applyTemplate(options.header, variables).trim(),
		options.partIndex,
		options.partTotal,
		options.format,
		variables.title,
		volume,
	);
	const footer = options.footer.trim() === "" ? "" : applyTemplate(options.footer, variables).trim();

	switch (options.format) {
		case "json": {
			const documents = units
				.filter((unit) => unit.role !== "preamble" && unit.role !== "footer")
				.map((unit) => {
					try {
						return JSON.parse(unit.content) as unknown;
					} catch {
						return { content: unit.content };
					}
				});
			const payload: Record<string, unknown> = {
				bundle: {
					title: variables.title,
					profile: options.profile.name,
					profileId: options.profile.id,
					format: "json",
					generatedAt: options.generatedAt.toISOString(),
					part: options.partIndex + 1,
					parts: options.partTotal,
					notes: options.stats.kept,
					words: options.stats.words,
					tokens: options.stats.tokens,
					preamble: units.filter((unit) => unit.role === "preamble").map((unit) => unit.content).join("\n\n") || undefined,
					footer: units.filter((unit) => unit.role === "footer").map((unit) => unit.content).join("\n\n") || undefined,
				},
				documents,
			};
			return JSON.stringify(payload, null, 2);
		}
		case "jsonl": {
			const lines: string[] = [];
			lines.push(
				JSON.stringify({
					type: "bundle",
					title: variables.title,
					profile: options.profile.name,
					profileId: options.profile.id,
					generatedAt: options.generatedAt.toISOString(),
					part: options.partIndex + 1,
					parts: options.partTotal,
					notes: options.stats.kept,
					words: options.stats.words,
					tokens: options.stats.tokens,
					header: header || undefined,
				}),
			);
			for (const unit of units) {
				if (unit.role === "preamble") {
					lines.push(JSON.stringify({ type: "preamble", text: unit.content }));
					continue;
				}
				if (unit.role === "footer") {
					lines.push(JSON.stringify({ type: "footer", text: unit.content }));
					continue;
				}
				lines.push(unit.content);
			}
			if (footer && !units.some((unit) => unit.role === "footer")) lines.push(JSON.stringify({ type: "footer", text: footer }));
			return lines.join("\n");
		}
		case "xml": {
			const documents = units.filter((unit) => unit.role !== "preamble" && unit.role !== "footer").map((unit) => unit.content);
			const preambleUnits = units.filter((unit) => unit.role === "preamble").map((unit) => unit.content).join("\n\n");
			const prologue = `<?xml version="1.0" encoding="UTF-8"?>\n<bundle title="${escapeXml(variables.title)}" profile="${escapeXml(
				options.profile.name,
			)}" generatedAt="${options.generatedAt.toISOString()}" part="${options.partIndex + 1}" parts="${options.partTotal}" notes="${
				options.stats.kept
			}" words="${options.stats.words}" tokens="${options.stats.tokens}">`;
			const preamble = [header, preambleUnits].filter((part) => part.trim() !== "").join("\n\n");
			const headerXml = preamble ? `\n  <preamble><![CDATA[${preamble.replace(/]]>/g, "]]]]><![CDATA[>")}]]></preamble>` : "";
			const footerXml = footer ? `\n  <postamble><![CDATA[${footer.replace(/]]>/g, "]]]]><![CDATA[>")}]]></postamble>` : "";
			return `${prologue}${headerXml}\n${documents.join("\n")}${footerXml}\n</bundle>`;
		}
		case "html": {
			const preambleHtml = units
				.filter((unit) => unit.role === "preamble")
				.map((unit) => unit.content)
				.join("\n");
			const documentsHtml = units
				.filter((unit) => unit.role !== "preamble" && unit.role !== "footer")
				.map((unit) => unit.content)
				.join("\n");
			return assembleHtmlDocument({
				title: variables.title,
				profileName: options.profile.name,
				partIndex: options.partIndex,
				partTotal: options.partTotal,
				stats: options.stats,
				generatedAt: options.generatedAt,
				preambleHtml,
				documentsHtml,
				footerText: footer,
			});
		}
		default: {
			const separator = options.includeNoteSeparators ? options.divider : "\n\n";
			const body = units
				.filter((unit) => unit.role !== "footer")
				.map((unit) => unit.content.trimEnd());
			// One blank line around the divider: joining the pieces with "\n\n"
			// *and* inserting a separator between them produced three.
			const chunks = [header, body.join(`\n\n${separator.trim()}\n\n`)];
			if (footer) chunks.push(footer);
			const text = chunks.filter((chunk) => chunk.trim() !== "").join("\n\n");
			return text.replace(/\n{4,}/g, "\n\n\n");
		}
	}
}

function appendPartNotice(
	header: string,
	index: number,
	total: number,
	format: ExportFormat,
	title: string,
	volume?: { index: number; total: number },
): string {
	if (total <= 1 && !volume) return header;
	const notice = [
		total > 1 ? `Part ${index + 1} of ${total}` : null,
		volume ? `volume ${volume.index} of ${volume.total}` : null,
	]
		.filter(Boolean)
		.join(" · ");
	switch (format) {
		case "markdown":
			return `${header}\n\n> 📦 **${notice}** — “${title}”`;
		case "plain":
			return `${header}\n${notice}`;
		default:
			return header;
	}
}

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                    */
/* -------------------------------------------------------------------------- */

function isoDate(ms: number): string {
	return new Date(ms).toISOString().slice(0, 10);
}

function escapeXml(text: string): string {
	return text.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&apos;" })[c] ?? c);
}

/** Rough markdown→text conversion for the `plain` format. */
export function stripMarkdown(text: string): string {
	return text
		.replace(/!\[([^\]]*)\]\([^)]*\)/g, "[image: $1]")
		.replace(/\[([^\]]*)\]\(([^)]*)\)/g, "$1 ($2)")
		.replace(/^\s{0,3}#{1,6}\s*/gm, "")
		.replace(/^\s*>\s?/gm, "")
		.replace(/(\*\*|__)(.*?)\1/g, "$2")
		.replace(/(\*|_)(?=\S)(.*?)(?<=\S)\1/g, "$2")
		.replace(/`{1,3}([^`]+)`{1,3}/g, "$1")
		.replace(/~~(.*?)~~/g, "$1")
		.replace(/^\s*([-*+])\s+/gm, "• ")
		.replace(/\n{3,}/g, "\n\n");
}

/** Lightweight, zero-dependency Markdown→HTML renderer for interactive HTML bundles. */
export function markdownToHtml(markdown: string): string {
	const lines = markdown.split(/\r?\n/);
	const out: string[] = [];
	let inCode = false;
	let codeLang = "";
	let codeLines: string[] = [];
	let inList = false;

	const closeList = () => {
		if (inList) {
			out.push("</ul>");
			inList = false;
		}
	};

	const formatInline = (raw: string): string => {
		let s = escapeXml(raw);
		s = s.replace(/`([^`]+)`/g, "<code>$1</code>");
		s = s.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
		s = s.replace(/\*([^*]+)\*/g, "<em>$1</em>");
		s = s.replace(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');
		return s;
	};

	for (const line of lines) {
		const fence = /^(`{3,}|~{3,})(.*)$/.exec(line.trim());
		if (fence) {
			closeList();
			if (!inCode) {
				inCode = true;
				codeLang = fence[2].trim();
				codeLines = [];
			} else {
				const cls = codeLang ? ` class="language-${escapeXml(codeLang)}"` : "";
				out.push(`<pre><code${cls}>${escapeXml(codeLines.join("\n"))}</code></pre>`);
				inCode = false;
				codeLang = "";
				codeLines = [];
			}
			continue;
		}
		if (inCode) {
			codeLines.push(line);
			continue;
		}
		const trimmed = line.trim();
		if (trimmed === "") {
			closeList();
			continue;
		}
		const heading = /^(#{1,6})\s+(.+)$/.exec(trimmed);
		if (heading) {
			closeList();
			const lvl = Math.min(6, heading[1].length);
			out.push(`<h${lvl}>${formatInline(heading[2])}</h${lvl}>`);
			continue;
		}
		const bullet = /^[-*+]\s+(.+)$/.exec(trimmed);
		if (bullet) {
			if (!inList) {
				out.push("<ul>");
				inList = true;
			}
			out.push(`<li>${formatInline(bullet[1])}</li>`);
			continue;
		}
		closeList();
		if (trimmed.startsWith(">")) {
			out.push(`<blockquote>${formatInline(trimmed.replace(/^>\s?/, ""))}</blockquote>`);
			continue;
		}
		out.push(`<p>${formatInline(trimmed)}</p>`);
	}
	closeList();
	if (inCode && codeLines.length > 0) {
		out.push(`<pre><code>${escapeXml(codeLines.join("\n"))}</code></pre>`);
	}
	return out.join("\n");
}

function assembleHtmlDocument(input: {
	title: string;
	profileName: string;
	partIndex: number;
	partTotal: number;
	stats: PlanStats;
	generatedAt: Date;
	preambleHtml: string;
	documentsHtml: string;
	footerText: string;
}): string {
	const partBadge = input.partTotal > 1 ? ` · Part ${input.partIndex + 1} of ${input.partTotal}` : "";
	const css = `
:root { --bg: #0f1117; --surface: #181b24; --border: #2a2f3d; --text: #e6e9f0; --muted: #9aa3b5; --accent: #7c6df2; --tag-bg: rgba(124,109,242,0.14); }
@media (prefers-color-scheme: light) { :root { --bg: #f7f8fa; --surface: #ffffff; --border: #e2e6ef; --text: #1c202b; --muted: #5e6678; --accent: #5848d6; --tag-bg: rgba(88,72,214,0.1); } }
* { box-sizing: border-box; }
body { margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }
.cve-shell { max-width: 980px; margin: 0 auto; padding: 24px 20px 64px; }
.cve-topbar { position: sticky; top: 0; z-index: 10; background: var(--surface); border-bottom: 1px solid var(--border); padding: 14px 20px; display: flex; flex-wrap: wrap; gap: 12px; align-items: center; justify-content: space-between; }
.cve-title { font-size: 1.15rem; font-weight: 700; margin: 0; }
.cve-stats { font-size: 0.85rem; color: var(--muted); }
.cve-search { padding: 7px 12px; border-radius: 6px; border: 1px solid var(--border); background: var(--bg); color: var(--text); min-width: 240px; font-size: 0.9rem; }
.cve-map, .cve-toc, .cve-doc { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 18px 22px; margin-bottom: 18px; }
.cve-doc-header { border-bottom: 1px solid var(--border); padding-bottom: 10px; margin-bottom: 14px; }
.cve-doc-title { margin: 0 0 6px; font-size: 1.25rem; }
.cve-doc-meta { font-size: 0.82rem; color: var(--muted); }
.cve-badge { display: inline-block; background: var(--accent); color: #fff; font-family: monospace; font-size: 0.78rem; padding: 1px 6px; border-radius: 4px; vertical-align: middle; }
.cve-tag { background: var(--tag-bg); color: var(--accent); padding: 1px 6px; border-radius: 4px; font-size: 0.78rem; }
pre { background: var(--bg); border: 1px solid var(--border); border-radius: 6px; padding: 12px; overflow-x: auto; }
code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 0.88em; }
blockquote { margin: 8px 0; padding-left: 12px; border-left: 3px solid var(--accent); color: var(--muted); }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.cve-footer { text-align: center; color: var(--muted); font-size: 0.85rem; margin-top: 32px; }
`.trim();
	const script = `
(function(){
  var input = document.getElementById('cve-search');
  if (!input) return;
  input.addEventListener('input', function(){
    var q = (input.value || '').toLowerCase().trim();
    var docs = document.querySelectorAll('.cve-doc');
    docs.forEach(function(el){
      if (!q) { el.style.display = ''; return; }
      var hay = (el.getAttribute('data-id') + ' ' + el.getAttribute('data-title') + ' ' + el.getAttribute('data-path') + ' ' + el.getAttribute('data-tags') + ' ' + el.textContent).toLowerCase();
      el.style.display = hay.indexOf(q) !== -1 ? '' : 'none';
    });
  });
})();
`.trim();
	return [
		`<!DOCTYPE html>`,
		`<html lang="en">`,
		`<head>`,
		`  <meta charset="UTF-8" />`,
		`  <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
		`  <title>${escapeXml(input.title)}${escapeXml(partBadge)}</title>`,
		`  <style>${css}</style>`,
		`</head>`,
		`<body>`,
		`  <header class="cve-topbar">`,
		`    <div>`,
		`      <h1 class="cve-title">${escapeXml(input.title)}${escapeXml(partBadge)}</h1>`,
		`      <div class="cve-stats"><strong>${escapeXml(input.profileName)}</strong> · ${formatCount(input.stats.kept)} notes · ${formatCount(input.stats.words)} words · ~${formatCount(input.stats.tokens)} tokens · ${escapeXml(input.generatedAt.toISOString().slice(0, 10))}</div>`,
		`    </div>`,
		`    <input id="cve-search" class="cve-search" type="search" placeholder="Filter notes by text, #tag, or S01…" />`,
		`  </header>`,
		`  <main class="cve-shell">`,
		input.preambleHtml,
		input.documentsHtml,
		input.footerText ? `    <footer class="cve-footer">${escapeXml(input.footerText)}</footer>` : "",
		`  </main>`,
		`  <script>${script}</script>`,
		`</body>`,
		`</html>`,
	]
		.filter(Boolean)
		.join("\n");
}

export { stringifyFrontmatter };
