/**
 * Profiles ("recipes") and their defaults.
 *
 * A profile is the whole configuration of an export: what to read, how to
 * clean it, how much to condense, how to package it and where to write it.
 * Instead of shipping ten unrelated toggles, the plugin ships a handful of
 * opinionated profiles that are known to work well with a specific
 * destination, and lets the user fork them.
 */

import type {
	BundleLimits,
	CondensationOptions,
	ExportProfile,
	FilterOptions,
	OrderOptions,
	OutputOptions,
	PackagingOptions,
	TransformOptions,
} from "./types";
import { LIMIT_PRESETS, UNLIMITED } from "./pack/limits";

/* -------------------------------------------------------------------------- */
/*  Defaults                                                                   */
/* -------------------------------------------------------------------------- */

export const DEFAULT_TRANSFORM: TransformOptions = {
	frontmatter: "metadata-card",
	metadataCardFields: [],
	wikilinks: "label",
	embeds: "transclude",
	transcludeDepth: 2,
	transcludeMaxChars: 20_000,
	attachments: "reference",
	inlineImageMaxBytes: 200_000,
	codeBlocks: "keep",
	stripHtmlComments: true,
	stripObsidianComments: true,
	stripDataviewBlocks: true,
	stripTemplaterExpressions: true,
	unwrapCallouts: true,
	tags: "keep",
	externalLinks: "keep",
	collapseBlankLines: 1,
	trimTrailingWhitespace: true,
	normalizeHeadingLevels: true,
	noteHeadingLevel: 2,
	dedupeTitleHeading: true,
	taskHandling: "keep",
	ensureTitle: true,
};

export const DEFAULT_FILTERS: FilterOptions = {
	tagsAll: [],
	tagsAny: [],
	tagsNone: [],
	minWords: 8,
	minWordsHard: null,
	maxWords: null,
	modifiedWithinDays: null,
	createdWithinDays: null,
	pathRegex: null,
	requireFrontmatterKey: null,
	excludeOutputFolder: true,
	maxFileMegabytes: 8,
	includeTextFiles: false,
	maxNotes: null,
	skipEmpty: true,
};

export const DEFAULT_ORDER: OrderOptions = {
	by: "path",
	direction: "asc",
	frontmatterKey: "order",
	groupByFolder: false,
	clusterSimilar: false,
};

export const DEFAULT_CONDENSATION: CondensationOptions = {
	dedupe: { enabled: true, mode: "collapse", threshold: 0.9, containmentThreshold: 0.93, minWords: 40 },
	boilerplate: { enabled: true, minDocs: 3, minLength: 10, blocks: true, maxRemovalRatio: 0.5 },
	summarize: {
		enabled: true,
		method: "centroid",
		mode: "ratio",
		ratio: 0.35,
		sentences: 8,
		minWords: 120,
		keepHeadings: true,
	},
	dropStubs: { enabled: true, maxWords: 12, linksOnly: true },
	inlineTransclusions: true,
};

export const DEFAULT_PACKAGING: PackagingOptions = {
	format: "markdown",
	chunking: {
		mode: "maxWords",
		maxChars: 1_000_000,
		maxTokens: 100_000,
		maxWords: 450_000,
		overlapTokens: 150,
		splitAtLevel: 2,
		repeatHeader: true,
	},
	includeToc: true,
	tocMaxDepth: 3,
	includeKnowledgeMap: true,
	includeGlossary: true,
	citationIds: true,
	headerTemplate: `# {{title}}

> **{{profile}}** · {{notes}} notes · {{words}} words · ~{{tokens}} tokens · generated {{date}}
> Source: {{roots}}`,
	footerTemplate: `*Generated by Condensated Vault Exporter — {{notes}} notes, {{words}} words, ~{{tokens}} tokens.*`,
	divider: "\n\n---\n\n",
	noteHeadingLevel: 2,
	includeManifest: true,
	manifestEmbedded: false,
	manifestSidecar: true,
	lineEnding: "lf",
};

export const DEFAULT_OUTPUT: OutputOptions = {
	destination: "vault",
	folder: "Exports",
	fileNameTemplate: "{{folder}} - {{date:}} {{profile}}",
	incremental: "off",
	openAfterExport: false,
	alsoCopyToClipboard: false,
};

export const UNLIMITED_LIMITS: BundleLimits = { ...UNLIMITED };

/* -------------------------------------------------------------------------- */
/*  Built-in profiles                                                          */
/* -------------------------------------------------------------------------- */

export interface ProfileRecipe {
	id: string;
	name: string;
	description: string;
	/** Long-form explanation shown in the profile editor. */
	rationale: string;
	build: () => ExportProfile;
}

function baseProfile(overrides: Partial<ExportProfile> & { id: string; name: string; description: string }): ExportProfile {
	return {
		targets: [],
		depth: -1,
		include: ["**/*.md"],
		exclude: [],
		filters: { ...DEFAULT_FILTERS },
		order: { ...DEFAULT_ORDER },
		transform: { ...DEFAULT_TRANSFORM },
		condensation: {
			...DEFAULT_CONDENSATION,
			dedupe: { ...DEFAULT_CONDENSATION.dedupe },
			boilerplate: { ...DEFAULT_CONDENSATION.boilerplate },
			summarize: { ...DEFAULT_CONDENSATION.summarize },
			dropStubs: { ...DEFAULT_CONDENSATION.dropStubs },
		},
		packaging: {
			...DEFAULT_PACKAGING,
			chunking: { ...DEFAULT_PACKAGING.chunking },
		},
		output: { ...DEFAULT_OUTPUT },
		limits: { ...UNLIMITED_LIMITS },
		...overrides,
	};
}

export const BUILTIN_PROFILES: ProfileRecipe[] = [
	{
		id: "notebooklm",
		name: "NotebookLM",
		description: "Condensed, deduplicated bundles sized for NotebookLM's per-source limits.",
		rationale:
			"NotebookLM accepts a limited number of sources with a word ceiling per source. This profile splits the corpus into parts that stay comfortably under those limits, adds a corpus map and citation ids so answers can point back to the right note, and collapses duplicates so the same idea is not counted twice.",
		build: () =>
			baseProfile({
				id: "notebooklm",
				name: "NotebookLM",
				description: "Condensed, deduplicated bundles sized for NotebookLM's per-source limits.",
				builtin: true,
				transform: { ...DEFAULT_TRANSFORM, wikilinks: "label", embeds: "transclude", frontmatter: "metadata-card" },
				packaging: {
					...DEFAULT_PACKAGING,
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "maxWords", maxWords: 450_000, overlapTokens: 200 },
					includeKnowledgeMap: true,
					includeGlossary: true,
					citationIds: true,
				},
				limits: { ...LIMIT_PRESETS[1].limits },
				output: { ...DEFAULT_OUTPUT, folder: "Exports/NotebookLM" },
			}),
	},
	{
		id: "chat-context",
		name: "Chat context",
		description: "One single file that fits a long-context chat prompt.",
		rationale:
			"Built for pasting into a chat with a large context window: everything condensed into one part under a token budget, with aggressive deduplication and summarization so the most valuable content survives.",
		build: () =>
			baseProfile({
				id: "chat-context",
				name: "Chat context",
				description: "One single file that fits a long-context chat prompt.",
				builtin: true,
				filters: { ...DEFAULT_FILTERS, skipEmpty: true },
				condensation: {
					...DEFAULT_CONDENSATION,
					dedupe: { enabled: true, mode: "skip", threshold: 0.86, containmentThreshold: 0.95, minWords: 40 },
					summarize: { ...DEFAULT_CONDENSATION.summarize, ratio: 0.28, minWords: 150 },
				},
				packaging: {
					...DEFAULT_PACKAGING,
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "maxTokens", maxTokens: 150_000, overlapTokens: 0 },
					includeToc: true,
					includeKnowledgeMap: true,
					includeGlossary: false,
				},
				limits: { ...LIMIT_PRESETS[3].limits },
				output: { ...DEFAULT_OUTPUT, folder: "Exports/Chat", alsoCopyToClipboard: true },
			}),
	},
	{
		id: "rag-chunks",
		name: "RAG chunks",
		description: "Many small parts (~1 000 tokens) ready for an embedding pipeline.",
		rationale:
			"Embedding pipelines work best with small, self-contained chunks. This profile splits the corpus into ~1 000-token parts with a small overlap, keeps the metadata intact (JSONL), and removes boilerplate so the embeddings capture content rather than templates.",
		build: () =>
			baseProfile({
				id: "rag-chunks",
				name: "RAG chunks",
				description: "Many small parts (~1 000 tokens) ready for an embedding pipeline.",
				builtin: true,
				transform: { ...DEFAULT_TRANSFORM, frontmatter: "keep", wikilinks: "label", embeds: "reference", tags: "keep" },
				condensation: {
					...DEFAULT_CONDENSATION,
					dedupe: { enabled: true, mode: "skip", threshold: 0.92, containmentThreshold: 0.96, minWords: 30 },
					summarize: { ...DEFAULT_CONDENSATION.summarize, enabled: false },
					dropStubs: { enabled: true, maxWords: 8, linksOnly: false },
				},
				packaging: {
					...DEFAULT_PACKAGING,
					format: "jsonl",
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "maxTokens", maxTokens: 1_000, overlapTokens: 120, splitAtLevel: 3 },
					includeToc: false,
					includeKnowledgeMap: false,
					includeGlossary: false,
					manifestSidecar: true,
				},
				limits: { ...LIMIT_PRESETS[4].limits },
				output: { ...DEFAULT_OUTPUT, folder: "Exports/RAG", fileNameTemplate: "{{folder}}-{{date}}-part-{{part}}" },
			}),
	},
	{
		id: "mirror",
		name: "Clean mirror",
		description: "One clean file per note — a processed copy of the folder.",
		rationale:
			"Sometimes the goal is not to merge but to *clean*: resolve transclusions, unwrap callouts, drop dataview noise, then write one file per note. This profile turns a messy vault into a tidy, portable Markdown mirror.",
		build: () =>
			baseProfile({
				id: "mirror",
				name: "Clean mirror",
				description: "One clean file per note — a processed copy of the folder.",
				builtin: true,
				condensation: {
					...DEFAULT_CONDENSATION,
					dedupe: { enabled: false, mode: "skip", threshold: 0.95, containmentThreshold: 0.97, minWords: 40 },
					summarize: { ...DEFAULT_CONDENSATION.summarize, enabled: false },
				},
				packaging: {
					...DEFAULT_PACKAGING,
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "perNote" },
					includeToc: false,
					includeKnowledgeMap: false,
					includeGlossary: false,
					manifestSidecar: true,
				},
				output: { ...DEFAULT_OUTPUT, folder: "Exports/Mirror", fileNameTemplate: "{{title}}" },
			}),
	},
	{
		id: "archive",
		name: "Full archive",
		description: "Everything, uncondensed, as a single searchable file.",
		rationale:
			"A faithful, lossless dump: no summaries, no deduplication, frontmatter kept verbatim, one big file. Useful for backup, grep or ingestion into a tool that does its own processing.",
		build: () =>
			baseProfile({
				id: "archive",
				name: "Full archive",
				description: "Everything, uncondensed, as a single searchable file.",
				builtin: true,
				transform: {
					...DEFAULT_TRANSFORM,
					frontmatter: "keep",
					wikilinks: "keep",
					embeds: "reference",
					stripDataviewBlocks: false,
					stripHtmlComments: false,
					stripObsidianComments: false,
					stripTemplaterExpressions: false,
					normalizeHeadingLevels: false,
					unwrapCallouts: false,
					dedupeTitleHeading: false,
					collapseBlankLines: 2,
				},
				condensation: {
					dedupe: { enabled: false, mode: "skip", threshold: 0.95, containmentThreshold: 0.97, minWords: 40 },
					boilerplate: { enabled: false, minDocs: 3, minLength: 14, blocks: false, maxRemovalRatio: 1 },
					summarize: { ...DEFAULT_CONDENSATION.summarize, enabled: false },
					dropStubs: { enabled: false, maxWords: 0, linksOnly: false },
					inlineTransclusions: false,
				},
				packaging: {
					...DEFAULT_PACKAGING,
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "single", maxWords: 0 },
					includeKnowledgeMap: false,
					includeGlossary: false,
					includeToc: true,
					manifestSidecar: false,
				},
				output: { ...DEFAULT_OUTPUT, folder: "Exports/Archive", fileNameTemplate: "{{folder}}-archive-{{date}}" },
			}),
	},
	{
		id: "study-guide",
		name: "Study guide",
		description: "Condensed notes plus an outline, a glossary and a reading order.",
		rationale:
			"Turns a folder of notes into study material: the corpus map lists key terms, definitions and a suggested reading order, while each note is trimmed to its essential sentences. The result reads like a chapter rather than a dump.",
		build: () =>
			baseProfile({
				id: "study-guide",
				name: "Study guide",
				description: "Condensed notes plus an outline, a glossary and a reading order.",
				builtin: true,
				order: { ...DEFAULT_ORDER, by: "centrality", direction: "desc", clusterSimilar: true },
				transform: {
					...DEFAULT_TRANSFORM,
					taskHandling: "dropDone",
					tags: "hoist",
					codeBlocks: "collapse",
				},
				condensation: {
					...DEFAULT_CONDENSATION,
					dedupe: { enabled: true, mode: "merge", threshold: 0.88, containmentThreshold: 0.95, minWords: 40 },
					summarize: {
						...DEFAULT_CONDENSATION.summarize,
						method: "keypoints",
						mode: "sentences",
						sentences: 12,
						minWords: 200,
						keepHeadings: true,
					},
				},
				packaging: {
					...DEFAULT_PACKAGING,
					includeKnowledgeMap: true,
					includeGlossary: true,
					includeToc: true,
					chunking: { ...DEFAULT_PACKAGING.chunking, mode: "maxTokens", maxTokens: 60_000 },
				},
				output: { ...DEFAULT_OUTPUT, folder: "Exports/Study" },
			}),
	},
];

/** Creates a fresh copy of a built-in profile (never shares mutable state). */
export function createBuiltinProfile(id: string): ExportProfile | undefined {
	const recipe = BUILTIN_PROFILES.find((entry) => entry.id === id);
	return recipe ? cloneProfile(recipe.build()) : undefined;
}

export function createDefaultProfiles(): ExportProfile[] {
	return BUILTIN_PROFILES.map((recipe) => cloneProfile(recipe.build()));
}

export function cloneProfile(profile: ExportProfile): ExportProfile {
	return deepClone(profile);
}

export function deepClone<T>(value: T): T {
	if (Array.isArray(value)) return value.map((item) => deepClone(item)) as unknown as T;
	if (value && typeof value === "object") {
		const out: Record<string, unknown> = {};
		for (const [key, entry] of Object.entries(value as Record<string, unknown>)) out[key] = deepClone(entry);
		return out as T;
	}
	return value;
}

/** Merges a stored (possibly older) profile with the current defaults. */
export function normalizeProfile(raw: Partial<ExportProfile>): ExportProfile {
	const fallbackName = raw.name ?? "Custom";
	const base =
		createBuiltinProfile(raw.id ?? "") ?? baseProfile({ id: raw.id ?? "custom", name: fallbackName, description: "" });
	const merged: ExportProfile = {
		...base,
		...raw,
		id: raw.id ?? base.id,
		name: raw.name ?? base.name,
		description: raw.description ?? base.description,
		targets: raw.targets ?? base.targets,
		include: raw.include ?? base.include,
		exclude: raw.exclude ?? base.exclude,
		filters: { ...base.filters, ...(raw.filters ?? {}) },
		order: { ...base.order, ...(raw.order ?? {}) },
		transform: { ...base.transform, ...(raw.transform ?? {}) },
		condensation: {
			...base.condensation,
			...(raw.condensation ?? {}),
			dedupe: { ...base.condensation.dedupe, ...(raw.condensation?.dedupe ?? {}) },
			boilerplate: { ...base.condensation.boilerplate, ...(raw.condensation?.boilerplate ?? {}) },
			summarize: { ...base.condensation.summarize, ...(raw.condensation?.summarize ?? {}) },
			dropStubs: { ...base.condensation.dropStubs, ...(raw.condensation?.dropStubs ?? {}) },
		},
		packaging: {
			...base.packaging,
			...(raw.packaging ?? {}),
			chunking: { ...base.packaging.chunking, ...(raw.packaging?.chunking ?? {}) },
		},
		output: { ...base.output, ...(raw.output ?? {}) },
		limits: { ...base.limits, ...(raw.limits ?? {}) },
	};
	delete (merged.transform as { tasks?: unknown }).tasks;
	return merged;
}

/** A one-line summary of a profile, shown in the profile list. */
export function describeProfile(profile: ExportProfile): string {
	const targets = profile.targets.length === 0 ? "the whole vault" : profile.targets.join(", ");
	const parts: string[] = [targets];
	switch (profile.packaging.chunking.mode) {
		case "single":
			parts.push("1 file");
			break;
		case "perNote":
			parts.push("1 file/note");
			break;
		case "perFolder":
			parts.push("1 file/folder");
			break;
		case "maxWords":
			parts.push(`≤${Math.round(profile.packaging.chunking.maxWords / 1000)}k words/part`);
			break;
		case "maxTokens":
			parts.push(`≤${Math.round(profile.packaging.chunking.maxTokens / 1000)}k tokens/part`);
			break;
		case "maxChars":
			parts.push(`≤${Math.round(profile.packaging.chunking.maxChars / 1000)}k chars/part`);
			break;
	}
	parts.push(profile.packaging.format);
	if (profile.condensation.summarize.enabled) parts.push("summaries");
	if (profile.condensation.dedupe.enabled) parts.push("dedupe");
	if (profile.transform.embeds === "transclude") parts.push("transclusions");
	return parts.join(" · ");
}
